apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pro2type-dispatcher
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/iivanov-soft2run/Pro2type.git
    targetRevision: HEAD
    path: pro2type-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true