apiVersion: database.do.crossplane.io/v1alpha1
kind: DODatabaseCluster
metadata:
  name: {{db_cluster_name}}
spec:
  forProvider:
    engine: pg
    version: "13"
    numNodes: 3
    size: db-s-2vcpu-4gb
    region: fra1
    tags:
      - "from-crossplane"
  providerConfigRef:
    name: do-crossplane-config