apiVersion: compute.do.crossplane.io/v1alpha1
kind: Droplet
metadata:
  name: {{resource_name}}
  annotations:
    crossplane.io/external-name: {{resource_name}}
spec:
  forProvider:
    region: fra1
    size: s-1vcpu-1gb
    image: ubuntu-20-04-x64
  providerConfigRef:
    name: do-crossplane-config